"""
screenwriter.py - The Creative AI

Uses Gemini Pro to generate unique "What if...?" alternative history scenarios.
Outputs: premise, location, and 3 timeline stages with descriptions.
"""

import os
import json
from datetime import datetime
from pathlib import Path
from typing import Optional
from dataclasses import dataclass, field, asdict

import yaml
from google import genai
from dotenv import load_dotenv

# Load environment variables
load_dotenv(override=True)


# Get project root directory
PROJECT_ROOT = Path(__file__).parent


def load_prompt(name: str) -> str:
    """Load a prompt from the prompts directory."""
    prompt_path = PROJECT_ROOT / "prompts" / f"{name}.md"
    if prompt_path.exists():
        return prompt_path.read_text(encoding='utf-8').strip()
    raise FileNotFoundError(f"Prompt file not found: {prompt_path}")


def load_model_config() -> dict:
    """Load model configuration from YAML file."""
    config_path = PROJECT_ROOT / "configs" / "model_config.yaml"
    if config_path.exists():
        with open(config_path, 'r', encoding='utf-8') as f:
            return yaml.safe_load(f)
    # Default config if file doesn't exist
    return {
        "gemini": {"model": "gemini-2.0-flash", "screenwriter": {"temperature": 0.95}}
    }


@dataclass
class StageData:
    """Data for a single timeline stage."""
    year: str
    label: str
    description: str
    mood: str
    image_prompt: str = ""  # Generated after combining with style


@dataclass
class Scenario:
    """Complete scenario data generated by the screenwriter."""
    id: str
    premise: str
    location_name: str
    location_prompt: str
    stage_1: StageData
    stage_2: StageData
    stage_3: StageData
    status: str = "PENDING"
    created_at: str = ""
    video_url: str = ""
    
    def __post_init__(self):
        if not self.created_at:
            self.created_at = datetime.now().isoformat()
        if not self.id:
            self.id = f"scenario_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
    
    def to_dict(self) -> dict:
        """Convert to dictionary for Sheets storage."""
        return {
            "id": self.id,
            "premise": self.premise,
            "location_name": self.location_name,
            "location_prompt": self.location_prompt,
            "stage_1_year": self.stage_1.year,
            "stage_1_label": self.stage_1.label,
            "stage_1_description": self.stage_1.description,
            "stage_1_mood": self.stage_1.mood,
            "stage_2_year": self.stage_2.year,
            "stage_2_label": self.stage_2.label,
            "stage_2_description": self.stage_2.description,
            "stage_2_mood": self.stage_2.mood,
            "stage_3_year": self.stage_3.year,
            "stage_3_label": self.stage_3.label,
            "stage_3_description": self.stage_3.description,
            "stage_3_mood": self.stage_3.mood,
            "status": self.status,
            "created_at": self.created_at,
            "video_url": self.video_url,
        }


class Screenwriter:
    """Generates alternative history scenarios using Gemini."""
    
    def __init__(self, api_key: Optional[str] = None):
        """Initialize with Gemini API key."""
        self.api_key = api_key or os.getenv("GOOGLE_API_KEY")
        if not self.api_key:
            raise ValueError("GOOGLE_API_KEY not found in environment")
        
        # Load model config
        self.config = load_model_config()
        gemini_config = self.config.get("gemini", {})
        self.model_name = gemini_config.get("model", "gemini-2.0-flash")
        self.temperature = gemini_config.get("screenwriter", {}).get("temperature", 0.95)
        
        # Initialize the new genai Client
        self.client = genai.Client(api_key=self.api_key)
        
        # Load prompt from file
        try:
            self.base_prompt = load_prompt("screenwriter")
        except FileNotFoundError:
            # Fallback to inline prompt if file doesn't exist
            self.base_prompt = self._get_default_prompt()
    
    def _get_default_prompt(self) -> str:
        """Fallback prompt if file not found."""
        return """You are a creative screenwriter for alternative history videos.
Generate a unique scenario with premise, location, and 3 stages.
Respond with valid JSON."""
    
    def generate_scenario(self, topic_hint: Optional[str] = None, 
                          avoid_premises: Optional[list] = None) -> Scenario:
        """
        Generate a new alternative history scenario.
        
        Args:
            topic_hint: Optional hint to guide the topic (e.g., "technology", "war", "nature")
            avoid_premises: List of existing premises to avoid generating duplicates
            
        Returns:
            Scenario object with all data
        """
        # Build the prompt from external file
        prompt = self.base_prompt
        if topic_hint:
            prompt += f"\n\nTopic hint: Focus on themes related to '{topic_hint}'"
        
        # Add existing premises to avoid
        if avoid_premises:
            prompt += "\n\n⚠️ CRITICAL: Do NOT generate any scenarios about these topics (already used):\n"
            for p in avoid_premises[:15]:  # Limit to 15 to not overwhelm context
                prompt += f"  - {p}\n"
            prompt += "\nGenerate something COMPLETELY DIFFERENT from the above topics."
        
        # Add today's date for context
        today = datetime.now().strftime("%B %d")
        prompt += f"\n\nToday's date: {today}. You may optionally tie the scenario to historical events near this date."
        
        # Generate using new Client API
        print("🎬 Screenwriter generating scenario...")
        response = self.client.models.generate_content(
            model=self.model_name,
            contents=prompt,
            config={
                'temperature': self.temperature,
                'response_mime_type': 'application/json'
            }
        )
        
        # Parse response
        try:
            data = json.loads(response.text)
        except json.JSONDecodeError as e:
            raise ValueError(f"Failed to parse Gemini response as JSON: {e}\nResponse: {response.text}")
        
        # Build Scenario object
        scenario = Scenario(
            id="",  # Will be auto-generated
            premise=data["premise"],
            location_name=data["location_name"],
            location_prompt=data["location_prompt"],
            stage_1=StageData(**data["stage_1"]),
            stage_2=StageData(**data["stage_2"]),
            stage_3=StageData(**data["stage_3"]),
        )
        
        print(f"✅ Generated: {scenario.premise}")
        print(f"   📍 Location: {scenario.location_name}")
        
        return scenario


def generate_scenario(topic_hint: Optional[str] = None, 
                     avoid_premises: Optional[list] = None) -> Scenario:
    """Convenience function to generate a scenario."""
    writer = Screenwriter()
    return writer.generate_scenario(topic_hint, avoid_premises)


if __name__ == "__main__":
    # Test the screenwriter
    print("\n" + "=" * 50)
    print("🎬 Testing Screenwriter")
    print("=" * 50)
    
    scenario = generate_scenario()
    
    print("\n📋 Full Scenario:")
    print(json.dumps(scenario.to_dict(), indent=2))
